#!/usr/bin/env bash

# run in bash to avoid issues with zsh not being installed yet

delete_flag=
while getopts d option; do
  case $option in
  d) delete_flag=1 ;;
  *) ;;
  esac
done

case $OSTYPE in
darwin*)
  if [ -n "$delete_flag" ]; then
    echo "Detected macOS. Removing macOS-specific dotfiles."
    stow --dotfiles -t "$HOME" -D shared -D mac
  else
    echo "Detected macOS. Installing macOS-specific dotfiles."
    stow --dotfiles -t "$HOME" shared mac
  fi
  ;;
linux*)
  if [ -n "$delete_flag" ]; then
    echo "Detected Linux. Removing dotfiles"
    stow --dotfiles -t "$HOME" -D shared -D linux
  else
    echo "Detected Linux. Installing dotfiles"
    stow --dotfiles -t "$HOME" shared linux
  fi
  ;;
*)
  echo "What is this OS? '$OSTYPE'"
  exit 1
  ;;
esac
