#!/usr/bin/env bash
source __tmux_utils

FZF_ARGS=(
  --delimiter /
  --with-nth -1
  --tmux
  --print-query
  --preview-window right,75%
  --preview-label-pos 5
  --bind "focus:transform-preview-label(__tmux_preview label {-1} {})+preview(__tmux_preview preview {-1} {})"
  --bind "zero:transform-preview-label(__tmux_preview new_session_label)+preview(__tmux_preview new_session_preview {q})"
  --bind "load:transform-preview-label(__tmux_preview label {-1} {})"
)

result=$({
  list_repos
  tmux list-sessions -F "#S"
} | fzf "${FZF_ARGS[@]}")

query=$(echo "$result" | head -1)
start_dir=$(echo "$result" | tail -n +2)
session_name=$(basename "$start_dir")

if [ -z "$query" ] && [ -z "$start_dir" ]; then
  exit 0
fi

if [ -z "$start_dir" ]; then
  session_name="$query"
fi

switch_or_create "$session_name" "${start_dir:-$HOME}"
