#!/usr/bin/env bash

key=$(jq -r '.provider.veikkaus.options.apiKey' $HOME/.config/opencode/opencode.json)

CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS='1' \
  DISABLE_TELEMETRY=1 \
  ANTHROPIC_BASE_URL="https://litellm.veikkaus.ai/" \
  ANTHROPIC_AUTH_TOKEN="${key}" claude
