#!/bin/sh

alias ls="eza"
alias la="eza -la --group-directories-first --git"
alias ll="eza -l --group-directories-first --git"
alias lt="eza -l --tree --git"
alias lta="eza -la --tree --git-ignore --git"

alias ssh="TERM=xterm-256color ssh"

# You never know what you might type
alias v="nvim"
alias vi="nvim"
alias vim="nvim"

alias vimdiff="nvim -d"
alias vd="nvim -d"

### Git stuff
# should check out git aliases as well
alias gil="git pull"
alias gip="git push"
alias gco="git checkout"
alias gs="git switch"
alias gsl="git log --abbrev-commit --oneline"
alias gl="git log"
alias gnb="git checkout -b"
alias gam="git commit -am" 
alias gm="git commit -m" 
alias gg="git status" 

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

function cd() {
  chdir $1 && ll
}
