#!/usr/bin/env zsh

path_list=(
    ~/repos/o
    ~/repos/clients/*
    ~/repos/wd
    ~/repos/exercism
    ~/.dotfiles/home/.local/user
    ~/.dotfiles/home
)

# Just a wrapper for tmux has-sessions. For brevity. Not really necessary
function has_session() {
    tmux has-session -t=$1 2> /dev/null
}

# Switch/attach to existing session based on whether already in tmux or not
function switch_or_attach() {
    # $1 => session_name
    if [[ -z $TMUX ]]; then 
        # Not in tmux, so we attach
        tmux attach-session -dt $1
    else
        # In tmux, can switch
        tmux detach-client -s $1
        tmux switch-client -t $1
    fi
}

if [[ $# -eq 1 ]]; then
    session_name=$1
    if has_session $1; then
        switch_or_attach $1
        exit 0
    else
        echo "Session '"$1"' doesn't exist"
        exit 1
    fi
else
    target_path=$(find $path_list -mindepth 1 -maxdepth 1 -type d | fzf --reverse)
fi

if [[ -z $target_path ]]; then
    exit 0
fi

session_name=${1:-$(basename $target_path | tr . _)}
tmux_running=$(pgrep tmux)

# Make sure tmux is running and that we have a session to connect/switch to
if [[ -z $tmux_running ]] || ! has_session $session_name; then
    tmux new-session -ds $session_name -c $target_path
fi

switch_or_attach $session_name
