#!/usr/bin/env bash

list_repos() {
  fd --hidden --type d --max-depth 5 --prune --glob .git $HOME/repos/ --exec dirname '{}'
}

session_exists() {
  tmux has-session -t "$1" 2>/dev/null
}

create_session() {
  tmux new-session -ds ${1} -c ${2}
}

attach_to() {
  if session_exists $1; then
    tmux detach-client -s "$1"
  fi

  if [[ -n "$TMUX" ]]; then
    tmux switch-client -t "$1"
  else
    tmux attach -t "$1"
  fi
}

send_command_to_session() {
  tmux send-keys -t"${1}:1" "${2}" Enter
}

switch_or_create() {
  local session="${1:?No session provided}"
  local start_dir="${2:-'#{pane_current_path}'}"

  if ! session_exists $session; then
    create_session $session $start_dir
    tmux split -t "${session}:1" -hb -c $start_dir
    send_command_to_session $session "${3:-v .}"
  fi

  attach_to $session
}

ssh_session() {
  local ssh_url=${1:?"no user@host spesified"}
  create_session $ssh_url $HOME
  send_command_to_session $ssh_url "ssh $ssh_url"
  switch_or_create $ssh_url
}

run_in_new_session() {
  local cmd=$(echo "$@" | cut -d " " -f1)
  local session="tmp_${cmd}_$(date +%s)"
  create_session $session '#{pane_current_path}'
  send_command_to_session $session "${@}"
  tmux switch-client -t $session
}

new_pane() {
  local pane_count=$(tmux display-message -p "#{window_panes}")
  tmux split-window -v -c "#{pane_current_path}" -t "$pane_count"
  tmux select-layout -E
}

git_branch() {
  local pane_path=$(tmux display-message -p "#{pane_current_path}")

  if git -C "$pane_path" rev-parse --git-dir &>/dev/null; then
    local branch=$(git -C "$pane_path" rev-parse --abbrev-ref HEAD)
    tmux set -g @git_info " $branch"
  else
    tmux set -g @git_info ""
  fi
}

set_prefix() {
  local TMUX_PREFIX="C-a"
  if [[ -n $SSH_CONNECTION ]]; then
    TMUX_PREFIX="C-s"
  fi

  tmux unbind-key C-b
  tmux set -g prefix $TMUX_PREFIX
  tmux bind-key $TMUX_PREFIX send-prefix
}

"$@"
