#!/usr/bin/env bash

list_repos() {
  fd --hidden --type d --max-depth 5 --prune --glob .git $HOME/repos/ --exec dirname '{}'
}

new_session() {
  result=$(tmux list-sessions -F "#S" | fzf --tmux)
}

switch_or_create() {
  session="${1:?No session provided. Usage: tmux_switch_or_create <session-name> <cwd>}"

  if tmux has-session -t "$session" 2>/dev/null; then
    tmux detach-client -s "$session" 2>/dev/null
  else
    start_dir="${2:?No path provided. Usage: tmux_switch_or_create <session-name> <cwd>}"
    tmux new-session -ds "$session" -c $start_dir
    tmux split -t "${session}:2" -hb -c $start_dir
    tmux send-keys -t "${session}:1" "v ." Enter
  fi

  if [[ -n "$TMUX" ]]; then
    tmux switch-client -t "$session"
  fi
}

new_pane() {
  pane_count=$(tmux display-message -p "#{window_panes}")
  tmux split-window -v -c "#{pane_current_path}" -t "$pane_count"
  tmux select-layout -E
}

git_branch() {
  pane_path=$(tmux display-message -p "#{pane_current_path}")

  if git -C "$pane_path" rev-parse --git-dir &>/dev/null; then
    branch=$(git -C "$pane_path" rev-parse --abbrev-ref HEAD)
    tmux set -g @git_info " $branch"
  else
    tmux set -g @git_info ""
  fi
}

init_repo() {
  tmux display-menu \
    "New repo" "n" "run-shell '__tmux_utils select_repo_path create_repo'" \
    "Clone a repo" "c" "run-shell '__tmux_utils select_repo_path clone_repo'"
}

select_repo_path() {
  tmux display-menu \
    "Own" "o" "run-shell '__tmux_utils $1 $HOME/repos/o'" \
    "Client" "c" "run-shell '__tmux_utils $1 $HOME/repos/clients'" \
    "WD" "w" "run-shell '__tmux_utils $1 $HOME/repos/wd'"
}

clone_repo() {
  #git clone $1 -o $2
  echo should clone repo now to $1
}

create_repo() {
  fzf --print-query --no-info --tmux
  echo should create new dir now to $1
  #mkdir -p $1/$2
  # Switch to new session
}

"$@"
