#!/usr/bin/env bash

default_repo_dir="$HOME/repos/"
start_directory="${1:-${REPO_SEARCH_DIR:-$default_repo_dir}}"

fd -t d -H "^\.git$" "$start_directory" 2>/dev/null | sed 's|/.git||' | sed 's|.*/repos/||' | sort
