#!/usr/bin/env bun

import { $ } from "bun";

type ModelResponse = {
  data: {
    id: string;
    created: number;
    owned_by: string;
    object: string;
  }[];
};

type ModelConf = {
  name: string;
  created?: number;
  limit: {
    context: number;
    output: number;
  };
};

type OpencodeConf = {
  provider: {
    [name: string]: {
      options: {
        baseURL: string;
        apiKey: string;
        apiKeyId: string;
      };
      models: {
        [modelId: string]: ModelConf;
      };
    };
  };
};

const modelBaseConf: Omit<ModelConf, "name"> = {
  limit: {
    context: 200000,
    output: 32000,
  },
};

const opencodeConf = (
  await $`echo $HOME/.config/opencode/opencode.json"`.text()
).trim();
const conf: OpencodeConf = JSON.parse(
  await Bun.file(opencodeConf.trim()).text(),
);

const { baseURL } = conf.provider.veikkaus.options;
const apiKey = await $`op read "op://Veikkaus/VeikkausAI API key/value"`.text();

const resp: ModelResponse = await (
  await fetch({
    url: `${baseURL}/models`,
    headers: {
      authorization: `Bearer ${apiKey}`,
    },
  })
).json();

const models: { [model: string]: ModelConf } = resp.data.reduce(
  (acc, model) => {
    const cur = conf.provider.veikkaus.models[model.id];
    if (cur && (cur.created ?? 0) < model.created) {
      acc[model.id] = {
        ...modelBaseConf,
        name: model.id,
        created: model.created,
      };
      console.log(`Model updated: "${model.id}" `);
    } else if (!cur) {
      acc[model.id] = {
        ...modelBaseConf,
        name: model.id,
        created: model.created,
      };
      console.log(`Model added: "${model.id}" `);
    } else {
      acc[model.id] = {
        ...modelBaseConf,
        name: cur.name,
        created: cur.created,
      };
    }
    return acc;
  },
  {} as { [model: string]: ModelConf },
);

const newConf: OpencodeConf = {
  ...conf,
  provider: {
    ...conf.provider,
    veikkaus: {
      ...conf.provider.veikkaus,
      models,
    },
  },
};

console.log("Writing current models to opencode.json");
//Bun.write(`${opencodeConf}_bak`, JSON.stringify(conf));
Bun.write(`${opencodeConf}`, JSON.stringify(newConf, null, 2));
