#!/usr/bin/env bun

import { $ } from "bun";

type ModelResponse = {
  data: {
    id: string;
    created: number;
  }[];
};

type ModelConf = {
  name: string;
  limit: {
    context: number;
    output: number;
  };
};

type OpencodeConf = {
  provider: {
    [name: string]: {
      options: {
        baseURL: string;
        apiKey: string;
        apiKeyId: string;
      };
      models: {
        [modelId: string]: ModelConf;
      };
    };
  };
};

const modelBaseConf: Omit<ModelConf, "name" | "release_date"> = {
  limit: {
    context: 200000,
    output: 32000,
  },
};

const opencodeConf = (
  await $`echo $HOME/.config/opencode/opencode.json"`.text()
).trim();
const conf: OpencodeConf = JSON.parse(
  await Bun.file(opencodeConf.trim()).text(),
);

const { baseURL, apiKeyId: onepasswordId } = conf.provider.veikkaus.options;
const apiKey =
  await $`op read "op://Veikkaus/VeikkausAI API key/value"`.text();

const resp: ModelResponse = await (
  await fetch({
    url: `${baseURL}/models`,
    headers: {
      authorization: `Bearer ${apiKey}`,
    },
  })
).json();

const models: { [model: string]: ModelConf } = resp.data.reduce(
  (acc, model) => {
    acc[model.id] = {
      ...modelBaseConf,
      name: model.id,
    };
    return acc;
  },
  {} as { [model: string]: ModelConf },
);

const newConf: OpencodeConf = {
  ...conf,
  provider: {
    ...conf.provider,
    veikkaus: {
      ...conf.provider.veikkaus,
      models,
    },
  },
};

console.log("Writing current models to opencode.json");
//Bun.write(`${opencodeConf}_bak`, JSON.stringify(conf));
Bun.write(`${opencodeConf}`, JSON.stringify(newConf, null, 2));
