#!/usr/bin/env bash

onepasswordId=$(jq -r '.provider.veikkaus.options.apiKeyId' $HOME/.config/opencode/opencode.json)
key=$(op item get ${onepasswordId} --fields "key" --reveal)

export ANTHROPIC_AUTH_TOKEN="${key}"

claude
