#!/bin/sh

#alias ls="ls --color=auto"
#alias la="ls -la --color=auto"
#alias ll="ls -l --color=auto"
alias ls="exa"
alias la="exa -la --group-directories-first"
alias ll="exa -l --group-directories-first"
alias lt="exa -l --tree"

alias ssh="TERM=xterm-256color ssh"

# You never know what you might type
alias v="nvim"
alias vi="nvim"
alias vim="nvim"

alias vimdiff="nvim -d"

### Git stuff
alias gil="git pull"
alias gip="git push"
alias gco="git checkout"
alias gs="git switch"
alias gsl="git log --abbrev-commit --oneline"
alias gnb="git checkout -b"
alias gcam="git commit -am" 

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

function cd() {
  chdir $1 && ll
}
