#!/bin/sh

alias ls="eza"
alias la="eza -la --group-directories-first"
alias ll="eza -l --group-directories-first"
alias lt="eza -l --tree"

alias ssh="TERM=xterm-256color ssh"

# You never know what you might type
alias v="nvim"
alias vi="nvim"
alias vim="nvim"

alias vimdiff="nvim -d"

### Git stuff
alias gil="git pull"
alias gip="git push"
alias gco="git checkout"
alias gs="git switch"
alias gsl="git log --abbrev-commit --oneline"
alias gnb="git checkout -b"
alias gcam="git commit -am" 

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

function cd() {
  chdir $1 && ll
}
