set -ga terminal-overrides ",screen-256color*:Tc"
set -g default-terminal "screen-256color"
set -g status-style 'bg=#333333 fg=#5eacd3'

# window numbering start from 1
set -g base-index 1
set -g pane-base-index 1
set-window-option pane-base-index 1
set -g renumber-windows on

unbind C-b
set -g prefix C-Space
bind-key C-Space send-prefix


set-window-option -g mode-keys vi


bind r source-file ~/.config/tmux/tmux.conf; display-message "Config reloaded"
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind v copy-mode
bind = select-layout tiled
bind q kill-pane

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# pane creation
bind -r K split-window -vb
bind -r J split-window -v
bind -r H split-window -hb
bind -r L split-window -h

# pane resize
# bind -r C-k resize-pane -U 5
# bind -r C-j resize-pane -D 5
# bind -r C-h resize-pane -L 5
# bind -r C-l resize-pane -R 5
# bind -r C-f resize-pane -Z

# forget the find window.  That is for chumps
# Based on the tms script by ThePrimagen
bind-key -r f popup -E ~/.local/user/scripts/tms

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.config/tmux/plugins/tpm/tpm'
