set -ga terminal-overrides ",screen-256color*:Tc"
set -g default-terminal "screen-256color"
set -g status-style 'bg=#333333 fg=#5eacd3'

# window numbering start from 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# enable mouse support
setw -g mouse on

set -g prefix C-a
# sensible tmux will set this but i'll have this here in case i forget to 
# install tpm on a new system
bind-key C-a send-prefix
# sensible unbinds the default prefix if new prefix is set, but this stays
# with the same reasoning as above
unbind C-b

set-window-option -g mode-keys vi

bind r source-file ~/.config/tmux/tmux.conf; display "config reloaded"

# vim-like copy
# prefix + v => enter copy mode
bind v copy-mode
# this is like vim's visual mode
bind -T copy-mode-vi v send-keys -X begin-selection
# and this is da yank
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

bind = select-layout main-vertical
bind q kill-pane

# pane creation
bind K split-window -vb -c "#{pane_current_path}"
bind J split-window -v -c "#{pane_current_path}"
bind H split-window -hb -c "#{pane_current_path}"
bind L split-window -h -c "#{pane_current_path}"


# pane resize
bind -r k resize-pane -U 5
bind -r j resize-pane -D 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5
# toggle "fullscreen"
bind -r C-f resize-pane -Z

# forget the find window.  That is for chumps
# Based on the tms script by ThePrimagen
bind-key -r f popup -E ~/.local/user/scripts/tms

# Styling
# Colors exported from .config/colorschemes/*
# Status line styling
set -g status-position top
set -g status-left-length 50
set -g status-style "fg=white, bg=default"

# Pane styling
set -g pane-border-lines double


# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.config/tmux/plugins/tpm/tpm'
