[metadata]
name = "repos"
requirements = ["fd", "git"]
description = """
A channel to select from git repositories on your local machine.

This channel uses `fd` to find directories that contain a `.git` subdirectory, and then allows you to preview the git log of the selected repository.
"""

[source]
command = "__list_repos"
display = "{split:/:-1}"

#[preview]
#command = "cd '{}'; git log -n 200 --pretty=medium --all --graph --color"

[keybindings]
enter = "actions:session"

[actions.session]
description = "Open a session in the selected repo"
command = "__tmux_switch_or_create '{split:/:-1}' '{}'"
mode = "execute"
